// Generated by scripts/build-lottery-line.mjs. Paste into a NEW dedicated spreadsheet-bound project.
var LOTTERY_INSTALL_PROPERTIES = {
  "LINE_LOGIN_CHANNEL_ID": "",
  "LOTTERY_SHEET_ID": "",
  "LOTTERY_CAMPAIGN_ID": "aroma-20261006",
  "LOTTERY_STARTS_AT": "2026-10-06T00:00:00+09:00",
  "LOTTERY_ENDS_AT": "2026-12-01T00:00:00+09:00",
  "LOTTERY_PRIZE_RULES": "[{\"id\":1,\"probability\":0.001,\"maxWinners\":3},{\"id\":2,\"probability\":0.333,\"maxWinners\":null},{\"id\":3,\"probability\":0.333,\"maxWinners\":null},{\"id\":4,\"probability\":0.333,\"maxWinners\":null}]",
  "LOTTERY_EXHAUSTED_PRIZE_POLICY": "equal_lower"
};

/**
 * Dedicated Google Apps Script project for the LINE lottery.
 * Do not paste into the existing LINE webhook project: both define doPost.
 * See docs/lottery-line-setup.md. No default campaign or win probability.
 */
var LOTTERY_HEADERS = ["campaign_id", "account_key", "outcome", "gem_index", "drawn_at", "draw_id"];
var LOTTERY_PRIZES = [
  { id: 1, rank: "1等", label: "施術90分無料" },
  { id: 2, rank: "2等", label: "衣装チェンジ無料" },
  { id: 3, rank: "3等", label: "写真指名無料" },
  { id: 4, rank: "4等", label: "パウダートリートメント無料" },
];

function lotteryPrizeRules_(raw) {
  var rules;
  try { rules = JSON.parse(raw || ""); } catch (_) { throw new Error("NOT_CONFIGURED"); }
  if (!Array.isArray(rules) || rules.length !== 4 || rules.some(function (rule) { return !rule || typeof rule !== "object" || Array.isArray(rule); })) throw new Error("NOT_CONFIGURED");
  rules.sort(function (a, b) { return a.id - b.id; });
  var sum = 0;
  for (var i = 0; i < 4; i++) {
    var rule = rules[i];
    if (!rule || rule.id !== i + 1 || typeof rule.probability !== "number" || !isFinite(rule.probability) ||
        rule.probability < 0 || rule.probability > 1 ||
        !(rule.maxWinners === null || (Number.isSafeInteger(rule.maxWinners) && rule.maxWinners >= 0)) ||
        (rule.id === 1 && rule.maxWinners !== 3)) throw new Error("NOT_CONFIGURED");
    sum += rule.probability;
  }
  if (!(sum > 0) || sum > 1 + 1e-12) throw new Error("NOT_CONFIGURED");
  return rules;
}

function lotteryConfig_() {
  var p = PropertiesService.getScriptProperties();
  var cfg = {
    campaignId: p.getProperty("LOTTERY_CAMPAIGN_ID"),
    channelId: p.getProperty("LINE_LOGIN_CHANNEL_ID"),
    sheetId: p.getProperty("LOTTERY_SHEET_ID"),
    startsAt: p.getProperty("LOTTERY_STARTS_AT"),
    endsAt: p.getProperty("LOTTERY_ENDS_AT"),
    prizeRules: lotteryPrizeRules_(p.getProperty("LOTTERY_PRIZE_RULES")),
    exhaustedPrizePolicy: p.getProperty("LOTTERY_EXHAUSTED_PRIZE_POLICY") || "lose",
  };
  if (!cfg.campaignId || !cfg.channelId || !cfg.sheetId ||
      !/^\d{4}-\d{2}-\d{2}T.*(?:Z|[+-]\d{2}:\d{2})$/.test(cfg.startsAt || "") ||
      !/^\d{4}-\d{2}-\d{2}T.*(?:Z|[+-]\d{2}:\d{2})$/.test(cfg.endsAt || "") ||
      !isFinite(Date.parse(cfg.startsAt)) || !isFinite(Date.parse(cfg.endsAt)) ||
      Date.parse(cfg.startsAt) >= Date.parse(cfg.endsAt)) {
    throw new Error("NOT_CONFIGURED");
  }
  if (["lose", "equal_lower"].indexOf(cfg.exhaustedPrizePolicy) < 0) throw new Error("NOT_CONFIGURED");
  if (cfg.exhaustedPrizePolicy === "equal_lower") {
    // Only the capped first prize can sell out in this no-losing campaign.
    var lowerProbability = (1 - cfg.prizeRules[0].probability) / 3;
    if (!(lowerProbability > 0) || cfg.prizeRules.slice(1).some(function (rule) {
      return rule.maxWinners !== null || Math.abs(rule.probability - lowerProbability) > 1e-12;
    })) throw new Error("NOT_CONFIGURED");
  }
  return cfg;
}

function lotteryJson_(value) {
  return ContentService.createTextOutput(JSON.stringify(value)).setMimeType(ContentService.MimeType.JSON);
}

function lotteryLineJson_(url, options) {
  var response = UrlFetchApp.fetch(url, Object.assign({ muteHttpExceptions: true }, options || {}));
  if (response.getResponseCode() !== 200) throw new Error("LINE_AUTH_FAILED");
  try { return JSON.parse(response.getContentText()); }
  catch (_) { throw new Error("LINE_AUTH_FAILED"); }
}

function lotteryIdentity_(request, cfg) {
  if (!request.idToken || !request.accessToken || request.idToken.length > 10000 || request.accessToken.length > 10000) {
    throw new Error("LINE_AUTH_FAILED");
  }
  // Verify signatures, expiry and audience using LINE, never trust a posted userId.
  var claims = lotteryLineJson_("https://api.line.me/oauth2/v2.1/verify", {
    method: "post", payload: { id_token: request.idToken, client_id: cfg.channelId },
  });
  if (claims.aud !== cfg.channelId || claims.iss !== "https://access.line.me" ||
      !/^U[0-9a-f]{32}$/.test(claims.sub || "") || !(Number(claims.exp) * 1000 > Date.now())) {
    throw new Error("LINE_AUTH_FAILED");
  }
  // This official verify endpoint requires the access_token query parameter.
  // Do not log the URL, tokens, profile, or request bodies.
  var access = lotteryLineJson_("https://api.line.me/oauth2/v2.1/verify?access_token=" + encodeURIComponent(request.accessToken));
  if (access.client_id !== cfg.channelId || !(Number(access.expires_in) > 0)) throw new Error("LINE_AUTH_FAILED");
  var headers = { Authorization: "Bearer " + request.accessToken };
  var profile = lotteryLineJson_("https://api.line.me/v2/profile", { headers: headers });
  if (profile.userId !== claims.sub) throw new Error("LINE_AUTH_FAILED");
  var friendship = lotteryLineJson_("https://api.line.me/friendship/v1/status", { headers: headers });
  if (typeof friendship.friendFlag !== "boolean") throw new Error("LINE_AUTH_FAILED");
  var hash = Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, cfg.campaignId + ":" + claims.sub, Utilities.Charset.UTF_8);
  var key = hash.map(function (byte) { return ("0" + ((byte + 256) % 256).toString(16)).slice(-2); }).join("");
  return { accountKey: key, friend: friendship.friendFlag };
}

/** Pure decision logic; the caller must hold the script lock through write+flush. */
function lotteryDecide_(request, rows, cfg, identity, now, random, newId) {
  if (request.campaignId !== cfg.campaignId || ["status", "draw"].indexOf(request.action) < 0) {
    return { response: { ok: false, error: "INVALID_REQUEST" } };
  }
  var campaignRows = rows.filter(function (row) { return row[0] === cfg.campaignId; });
  var seen = {};
  var damaged = campaignRows.some(function (row) {
    if (!/^[a-f0-9]{64}$/.test(row[1] || "") || ["win", "lose", "prize_1", "prize_2", "prize_3", "prize_4"].indexOf(row[2]) < 0 ||
        [0, 1, 2].indexOf(Number(row[3])) < 0 || row[3] === "" || row[3] == null ||
        !isFinite(Date.parse(row[4])) || !row[5] || seen[row[1]]) return true;
    seen[row[1]] = true;
    return false;
  });
  if (damaged) return { response: { ok: false, error: "DATA_ERROR" } };
  var previous = campaignRows.find(function (row) { return row[1] === identity.accountKey; });
  if (previous) {
    return { response: { ok: true, result: lotteryResult_(previous), repeated: true } };
  }
  if (!identity.friend) return { response: { ok: false, error: "FRIEND_REQUIRED" } };
  if (now < Date.parse(cfg.startsAt)) return { response: { ok: false, error: "NOT_STARTED" } };
  if (now >= Date.parse(cfg.endsAt)) return { response: { ok: false, error: "ENDED" } };
  var available = cfg.prizeRules.filter(function (rule) {
    var count = campaignRows.filter(function (row) { return row[2] === "prize_" + rule.id || (rule.id === 1 && row[2] === "win"); }).length;
    return rule.probability > 0 && (rule.maxWinners === null || count < rule.maxWinners);
  });
  if (available.length === 0) return { response: { ok: false, error: "SOLD_OUT" } };
  if (request.action === "status") return { response: { ok: true, eligible: true } };
  var gemIndex = Number(request.gemIndex);
  if (!/^[012]$/.test(String(request.gemIndex)) || [0, 1, 2].indexOf(gemIndex) < 0) {
    return { response: { ok: false, error: "INVALID_REQUEST" } };
  }
  var sample = random(), threshold = 0, outcome = "lose";
  var equalLower = cfg.exhaustedPrizePolicy === "equal_lower";
  var firstAvailable = available.some(function (rule) { return rule.id === 1; });
  for (var index = 0; index < available.length; index++) {
    threshold += equalLower && !firstAvailable ? 1 / 3 : available[index].probability;
    if (sample < threshold) { outcome = "prize_" + available[index].id; break; }
  }
  // Floating-point rounding must not create a losing result in this policy.
  if (equalLower && outcome === "lose") outcome = "prize_" + available[available.length - 1].id;
  var row = [cfg.campaignId, identity.accountKey, outcome, gemIndex, new Date(now).toISOString(), newId()];
  return { row: row, response: { ok: true, result: lotteryResult_(row), repeated: false } };
}

function lotteryResult_(row) {
  // Preserve old rows: the previously unranked free-treatment winner is rank 1.
  var prizeId = row[2] === "win" ? 1 : row[2] === "lose" ? null : Number(row[2].slice(6));
  var prize = LOTTERY_PRIZES.find(function (item) { return item.id === prizeId; });
  return { outcome: prize ? "win" : "lose", prizeId: prizeId, prizeLabel: prize ? prize.label : null, gemIndex: Number(row[3]), drawnAt: row[4], drawId: row[5] };
}

function lotterySheet_(cfg) {
  var book = SpreadsheetApp.openById(cfg.sheetId);
  var sheet = book.getSheetByName("抽選参加台帳");
  if (!sheet) {
    sheet = book.insertSheet("抽選参加台帳");
    sheet.appendRow(LOTTERY_HEADERS);
    sheet.setFrozenRows(1);
  }
  var values = sheet.getDataRange().getValues();
  if (JSON.stringify(values[0]) !== JSON.stringify(LOTTERY_HEADERS)) throw new Error("DATA_ERROR");
  return { sheet: sheet, rows: values.slice(1) };
}

function doPost(e) {
  var lock = null;
  try {
    var cfg = lotteryConfig_();
    var request = e && e.parameter || {};
    if (request.campaignId !== cfg.campaignId || ["status", "draw"].indexOf(request.action) < 0) {
      return lotteryJson_({ ok: false, error: "INVALID_REQUEST" });
    }
    var identity = lotteryIdentity_(request, cfg);
    lock = LockService.getScriptLock();
    if (!lock.tryLock(10000)) return lotteryJson_({ ok: false, error: "BUSY" });
    var data = lotterySheet_(cfg);
    var decision = lotteryDecide_(request, data.rows, cfg, identity, Date.now(), Math.random, function () { return Utilities.getUuid(); });
    if (decision.row) {
      data.sheet.appendRow(decision.row);
      SpreadsheetApp.flush(); // Persist before releasing the lock or returning a result.
    }
    return lotteryJson_(decision.response);
  } catch (error) {
    var known = ["NOT_CONFIGURED", "LINE_AUTH_FAILED", "DATA_ERROR"];
    // No raw exception output: URL/token or spreadsheet details may be sensitive.
    return lotteryJson_({ ok: false, error: known.indexOf(error.message) >= 0 ? error.message : "SERVER_ERROR" });
  } finally {
    if (lock && lock.hasLock()) lock.releaseLock();
  }
}

function doGet() {
  // Authenticated operations are POST only; do not accept tokens in a client URL.
  return lotteryJson_({ ok: false, error: "POST_REQUIRED" });
}

/** Run setupLottery from a new spreadsheet's bound Apps Script project. */
function setupLottery() {
  var book = SpreadsheetApp.getActiveSpreadsheet();
  if (!book) throw new Error("抽選専用スプレッドシートの「拡張機能 → Apps Script」から実行してください。");
  var ui = SpreadsheetApp.getUi();
  var input = ui.prompt("抽選のLINE接続設定", "LINEログインチャネルID（数字）を入力してください。Messaging APIのIDやチャネルシークレットではありません。", ui.ButtonSet.OK_CANCEL);
  if (input.getSelectedButton() !== ui.Button.OK) return;
  var channelId = input.getResponseText().trim();
  if (!/^\d+$/.test(channelId)) throw new Error("LINEログインチャネルIDを数字で入力してください。");
  var properties = PropertiesService.getScriptProperties();
  var next = Object.assign({}, LOTTERY_INSTALL_PROPERTIES, {
    LINE_LOGIN_CHANNEL_ID: channelId, LOTTERY_SHEET_ID: book.getId(),
  });
  var lock = LockService.getScriptLock();
  if (!lock.tryLock(10000)) throw new Error("別の処理が実行中です。少し待ってからやり直してください。");
  try {
    // Never reset a ledger or silently change the identity of an existing campaign.
    ["LOTTERY_CAMPAIGN_ID", "LINE_LOGIN_CHANNEL_ID", "LOTTERY_SHEET_ID"].forEach(function (key) {
      var existing = properties.getProperty(key);
      if (existing && existing !== next[key]) throw new Error("既存の接続設定と一致しません。別の抽選専用プロジェクトを使用してください。");
    });
    lotterySheet_({ sheetId: next.LOTTERY_SHEET_ID });
    SpreadsheetApp.flush();
    properties.setProperties(next, false);
  } finally {
    if (lock.hasLock()) lock.releaseLock();
  }
  ui.alert("抽選設定を保存しました。次に「デプロイ → 新しいデプロイ → ウェブアプリ」で公開し、末尾が /exec のURLを控えてください。まだLINEからの接続確認は完了していません。");
}
